# This is a basic workflow to help you get started with Actions

name: Bump version

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
#     paths-ignore:
#       - 'VERSION' # todo: also ignore badge
      
  pull_request:
    branches: [ main ]
#     paths-ignore:
#       - 'VERSION' # todo: also ignore badge

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          git-message: 'chore(release): {version}' # Commit message that is used when committing the changelog.
          git-user-name: 'Awesome Changelog Action'
          git-user-email: 'awesome_changelog@github.actions.com'
          git-pull-method: --ff-only
          preset: 'angular' # Preset that is used from conventional commits.
          tag-prefix: 'v' # Prefix for the git tags.
          release-count: '10' # Number of releases to preserve in changelog. Default 5, use 0 to regenerate all.
          version-file: 'VERSION.json'
          version-path: 'version'
          output-file: 'false' # File to output the changelog to. Default CHANGELOG.md, when providing 'false' no file will be generated / updated.
          skip-on-empty: 'false' # Boolean to specify if you want to skip empty release (no-changelog generated).
          skip-version-file: 'false' # Do not update the version file.
          skip-commit: 'false' # Do not create a release commit. 
          
          
      - name: Create Release
        uses: actions/create-release@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
